# Edition
edition = "2024"

# Maximum line width
max_width = 100

# Use 4 spaces for indentation
tab_spaces = 4

# Import ordering
reorder_imports = true
reorder_modules = true

# These settings work on stable:
use_small_heuristics = "Default"